# Generated by Django 2.0.3 on 2018-07-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
